require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DesignatedNationalAuthoritiesController do

  # This should return the minimal set of attributes required to create a valid
  # DesignatedNationalAuthority. As you add validations to DesignatedNationalAuthority, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DesignatedNationalAuthoritiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all designated_national_authorities as @designated_national_authorities" do
      designated_national_authority = DesignatedNationalAuthority.create! valid_attributes
      get :index, {}, valid_session
      assigns(:designated_national_authorities).should eq([designated_national_authority])
    end
  end

  describe "GET show" do
    it "assigns the requested designated_national_authority as @designated_national_authority" do
      designated_national_authority = DesignatedNationalAuthority.create! valid_attributes
      get :show, {:id => designated_national_authority.to_param}, valid_session
      assigns(:designated_national_authority).should eq(designated_national_authority)
    end
  end

  describe "GET new" do
    it "assigns a new designated_national_authority as @designated_national_authority" do
      get :new, {}, valid_session
      assigns(:designated_national_authority).should be_a_new(DesignatedNationalAuthority)
    end
  end

  describe "GET edit" do
    it "assigns the requested designated_national_authority as @designated_national_authority" do
      designated_national_authority = DesignatedNationalAuthority.create! valid_attributes
      get :edit, {:id => designated_national_authority.to_param}, valid_session
      assigns(:designated_national_authority).should eq(designated_national_authority)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DesignatedNationalAuthority" do
        expect {
          post :create, {:designated_national_authority => valid_attributes}, valid_session
        }.to change(DesignatedNationalAuthority, :count).by(1)
      end

      it "assigns a newly created designated_national_authority as @designated_national_authority" do
        post :create, {:designated_national_authority => valid_attributes}, valid_session
        assigns(:designated_national_authority).should be_a(DesignatedNationalAuthority)
        assigns(:designated_national_authority).should be_persisted
      end

      it "redirects to the created designated_national_authority" do
        post :create, {:designated_national_authority => valid_attributes}, valid_session
        response.should redirect_to(DesignatedNationalAuthority.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved designated_national_authority as @designated_national_authority" do
        # Trigger the behavior that occurs when invalid params are submitted
        DesignatedNationalAuthority.any_instance.stub(:save).and_return(false)
        post :create, {:designated_national_authority => {}}, valid_session
        assigns(:designated_national_authority).should be_a_new(DesignatedNationalAuthority)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DesignatedNationalAuthority.any_instance.stub(:save).and_return(false)
        post :create, {:designated_national_authority => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested designated_national_authority" do
        designated_national_authority = DesignatedNationalAuthority.create! valid_attributes
        # Assuming there are no other designated_national_authorities in the database, this
        # specifies that the DesignatedNationalAuthority created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DesignatedNationalAuthority.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => designated_national_authority.to_param, :designated_national_authority => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested designated_national_authority as @designated_national_authority" do
        designated_national_authority = DesignatedNationalAuthority.create! valid_attributes
        put :update, {:id => designated_national_authority.to_param, :designated_national_authority => valid_attributes}, valid_session
        assigns(:designated_national_authority).should eq(designated_national_authority)
      end

      it "redirects to the designated_national_authority" do
        designated_national_authority = DesignatedNationalAuthority.create! valid_attributes
        put :update, {:id => designated_national_authority.to_param, :designated_national_authority => valid_attributes}, valid_session
        response.should redirect_to(designated_national_authority)
      end
    end

    describe "with invalid params" do
      it "assigns the designated_national_authority as @designated_national_authority" do
        designated_national_authority = DesignatedNationalAuthority.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DesignatedNationalAuthority.any_instance.stub(:save).and_return(false)
        put :update, {:id => designated_national_authority.to_param, :designated_national_authority => {}}, valid_session
        assigns(:designated_national_authority).should eq(designated_national_authority)
      end

      it "re-renders the 'edit' template" do
        designated_national_authority = DesignatedNationalAuthority.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DesignatedNationalAuthority.any_instance.stub(:save).and_return(false)
        put :update, {:id => designated_national_authority.to_param, :designated_national_authority => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested designated_national_authority" do
      designated_national_authority = DesignatedNationalAuthority.create! valid_attributes
      expect {
        delete :destroy, {:id => designated_national_authority.to_param}, valid_session
      }.to change(DesignatedNationalAuthority, :count).by(-1)
    end

    it "redirects to the designated_national_authorities list" do
      designated_national_authority = DesignatedNationalAuthority.create! valid_attributes
      delete :destroy, {:id => designated_national_authority.to_param}, valid_session
      response.should redirect_to(designated_national_authorities_url)
    end
  end

end
