require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HostProjectParticipantsController do

  # This should return the minimal set of attributes required to create a valid
  # HostProjectParticipant. As you add validations to HostProjectParticipant, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HostProjectParticipantsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all host_project_participants as @host_project_participants" do
      host_project_participant = HostProjectParticipant.create! valid_attributes
      get :index, {}, valid_session
      assigns(:host_project_participants).should eq([host_project_participant])
    end
  end

  describe "GET show" do
    it "assigns the requested host_project_participant as @host_project_participant" do
      host_project_participant = HostProjectParticipant.create! valid_attributes
      get :show, {:id => host_project_participant.to_param}, valid_session
      assigns(:host_project_participant).should eq(host_project_participant)
    end
  end

  describe "GET new" do
    it "assigns a new host_project_participant as @host_project_participant" do
      get :new, {}, valid_session
      assigns(:host_project_participant).should be_a_new(HostProjectParticipant)
    end
  end

  describe "GET edit" do
    it "assigns the requested host_project_participant as @host_project_participant" do
      host_project_participant = HostProjectParticipant.create! valid_attributes
      get :edit, {:id => host_project_participant.to_param}, valid_session
      assigns(:host_project_participant).should eq(host_project_participant)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HostProjectParticipant" do
        expect {
          post :create, {:host_project_participant => valid_attributes}, valid_session
        }.to change(HostProjectParticipant, :count).by(1)
      end

      it "assigns a newly created host_project_participant as @host_project_participant" do
        post :create, {:host_project_participant => valid_attributes}, valid_session
        assigns(:host_project_participant).should be_a(HostProjectParticipant)
        assigns(:host_project_participant).should be_persisted
      end

      it "redirects to the created host_project_participant" do
        post :create, {:host_project_participant => valid_attributes}, valid_session
        response.should redirect_to(HostProjectParticipant.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved host_project_participant as @host_project_participant" do
        # Trigger the behavior that occurs when invalid params are submitted
        HostProjectParticipant.any_instance.stub(:save).and_return(false)
        post :create, {:host_project_participant => {}}, valid_session
        assigns(:host_project_participant).should be_a_new(HostProjectParticipant)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HostProjectParticipant.any_instance.stub(:save).and_return(false)
        post :create, {:host_project_participant => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested host_project_participant" do
        host_project_participant = HostProjectParticipant.create! valid_attributes
        # Assuming there are no other host_project_participants in the database, this
        # specifies that the HostProjectParticipant created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HostProjectParticipant.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => host_project_participant.to_param, :host_project_participant => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested host_project_participant as @host_project_participant" do
        host_project_participant = HostProjectParticipant.create! valid_attributes
        put :update, {:id => host_project_participant.to_param, :host_project_participant => valid_attributes}, valid_session
        assigns(:host_project_participant).should eq(host_project_participant)
      end

      it "redirects to the host_project_participant" do
        host_project_participant = HostProjectParticipant.create! valid_attributes
        put :update, {:id => host_project_participant.to_param, :host_project_participant => valid_attributes}, valid_session
        response.should redirect_to(host_project_participant)
      end
    end

    describe "with invalid params" do
      it "assigns the host_project_participant as @host_project_participant" do
        host_project_participant = HostProjectParticipant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HostProjectParticipant.any_instance.stub(:save).and_return(false)
        put :update, {:id => host_project_participant.to_param, :host_project_participant => {}}, valid_session
        assigns(:host_project_participant).should eq(host_project_participant)
      end

      it "re-renders the 'edit' template" do
        host_project_participant = HostProjectParticipant.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HostProjectParticipant.any_instance.stub(:save).and_return(false)
        put :update, {:id => host_project_participant.to_param, :host_project_participant => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested host_project_participant" do
      host_project_participant = HostProjectParticipant.create! valid_attributes
      expect {
        delete :destroy, {:id => host_project_participant.to_param}, valid_session
      }.to change(HostProjectParticipant, :count).by(-1)
    end

    it "redirects to the host_project_participants list" do
      host_project_participant = HostProjectParticipant.create! valid_attributes
      delete :destroy, {:id => host_project_participant.to_param}, valid_session
      response.should redirect_to(host_project_participants_url)
    end
  end

end
